version: '3'
services:
  
  springboot: 
    image: openjdk:17
    tty: true
    volumes:
      - ./onlineshop:/srv:cached
    working_dir: /srv
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: springboot-mysql
    volumes:
      - ./mysql/log/:/var/lib/mysql
    ports:
      - 3336:3306
    environment:
      MYSQL_DATABASE: "OnlineShop" # この場合sampleというデータベースが作成されます
      MYSQL_ROOT_USER: "root" # rootユーザーはパスワードを設定しないとエラーでます
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"

  react:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: react-fornt
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/app:cached
    tty: true
    command: sh -c 'cd front && yarn start'
    stdin_open: true