version: '3'
services:
  
  springboot: 
    image: openjdk:17
    tty: true
    volumes:
      - ./onlineshop:/srv:cached
    working_dir: /srv
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    container_name: springboot-mysql
    volumes:
      - ./mysql/log/:/var/lib/mysql
    ports:
      - 3336:3306
    environment:
      MYSQL_DATABASE: OnlineShop # この場合sampleというデータベースが作成されます
      MYSQL_ROOT_USER: root # rootユーザーはパスワードを設定しないとエラーでます
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"

  react:
    container_name: react-web-app
    image: node:17-alpine
    volumes:
      - ./front:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'
    stdin_open: true